package telas;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import controle.ConfigProperties;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfigJFrame.java
 *
 * Created on 14/06/2010, 08:42:05
 */

/**
 *
 * @author Rodolfo
 */
public class ConfigWindow extends javax.swing.JFrame {

    /** Creates new form ConfigJFrame 
     * @param configuration */
	ConfigProperties configuration;
    public ConfigWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * @param configuration 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tropicalBiomassJTextField = new javax.swing.JTextField();
        temperateBiomassJTextField = new javax.swing.JTextField();
        borealBiomassJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        shrubBiomassJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gramineaBiomassJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        shrubMaxLaiJTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        gramineaMaxLaiJTextField = new javax.swing.JTextField();
        tropicalMaxLaiJTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        temperateMaxLaiJTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        borealMaxLaiJTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        aglbLimitJTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        salvarJButton = new javax.swing.JButton();
        resetarJButton = new javax.swing.JButton();
        cancelarJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(false);
        setAlwaysOnTop(false);

        jLabel1.setText("Interval for Biomass Number");

        jLabel2.setText("Tropical");

        tropicalBiomassJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tropicalBiomassJTextFieldActionPerformed(evt);
            }
        });

        temperateBiomassJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperateBiomassJTextFieldActionPerformed(evt);
            }
        });

        borealBiomassJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borealBiomassJTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Temperate");

        jLabel4.setText("Boreal");

        jLabel5.setText("Shrub");

        shrubBiomassJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shrubBiomassJTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Graminea");

        gramineaBiomassJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gramineaBiomassJTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Max Lai");

        jLabel8.setText("Tropical");

        jLabel9.setText("Shrub");

        shrubMaxLaiJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shrubMaxLaiJTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Graminea");

        gramineaMaxLaiJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gramineaMaxLaiJTextFieldActionPerformed(evt);
            }
        });

        tropicalMaxLaiJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tropicalMaxLaiJTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Temperate");

        temperateMaxLaiJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperateMaxLaiJTextFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Boreal");

        borealMaxLaiJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borealMaxLaiJTextFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("Max Number of Models");

        aglbLimitJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aglbLimitJTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("All models");

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	salvarJButtonActionPerformed(evt);
            }
        });

        resetarJButton.setText("Resetar");
        resetarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetLabels();
            }

			private void resetLabels() {
				tropicalBiomassJTextField.setText("");
				tropicalMaxLaiJTextField.setText("");
				temperateBiomassJTextField.setText("");
				temperateMaxLaiJTextField.setText("");
				borealBiomassJTextField.setText("");
				borealMaxLaiJTextField.setText("");
				shrubBiomassJTextField.setText("");
				shrubMaxLaiJTextField.setText("");
				gramineaBiomassJTextField.setText("");
				gramineaMaxLaiJTextField.setText("");
				aglbLimitJTextField.setText("");
				
				
				
			}
        });

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	cancelarJButtonActionPerformed(evt);
            	
            }

			private void cancelarJButtonActionPerformed(ActionEvent evt) {
				setVisible(false);
				
			}});
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(shrubBiomassJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(gramineaBiomassJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tropicalBiomassJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(7, 7, 7)
                                        .addComponent(temperateBiomassJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(7, 7, 7)
                                        .addComponent(borealBiomassJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(shrubMaxLaiJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(gramineaMaxLaiJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tropicalMaxLaiJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addGap(7, 7, 7)
                                        .addComponent(temperateMaxLaiJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(7, 7, 7)
                                        .addComponent(borealMaxLaiJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aglbLimitJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(salvarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(temperateBiomassJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(borealBiomassJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tropicalBiomassJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(shrubBiomassJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gramineaBiomassJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(temperateMaxLaiJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(borealMaxLaiJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tropicalMaxLaiJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(shrubMaxLaiJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gramineaMaxLaiJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(aglbLimitJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarJButton)
                    .addComponent(resetarJButton)
                    .addComponent(cancelarJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tropicalBiomassJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tropicalBiomassJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tropicalBiomassJTextFieldActionPerformed

    private void temperateBiomassJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperateBiomassJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_temperateBiomassJTextFieldActionPerformed

    private void borealBiomassJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borealBiomassJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_borealBiomassJTextFieldActionPerformed

    private void shrubBiomassJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shrubBiomassJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_shrubBiomassJTextFieldActionPerformed

    private void gramineaBiomassJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gramineaBiomassJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_gramineaBiomassJTextFieldActionPerformed

    private void shrubMaxLaiJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shrubMaxLaiJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_shrubMaxLaiJTextFieldActionPerformed

    private void gramineaMaxLaiJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gramineaMaxLaiJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_gramineaMaxLaiJTextFieldActionPerformed

    private void tropicalMaxLaiJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tropicalMaxLaiJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tropicalMaxLaiJTextFieldActionPerformed

    private void temperateMaxLaiJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperateMaxLaiJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_temperateMaxLaiJTextFieldActionPerformed

    private void borealMaxLaiJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borealMaxLaiJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_borealMaxLaiJTextFieldActionPerformed

    private void aglbLimitJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aglbLimitJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_aglbLimitJTextFieldActionPerformed

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	try{
    		
    		double[] newValues = {Double.parseDouble(tropicalBiomassJTextField.getText()), Double.parseDouble(temperateBiomassJTextField.getText()),
        			Double.parseDouble( borealBiomassJTextField.getText()), Double.parseDouble( shrubBiomassJTextField.getText()), Double.parseDouble( gramineaBiomassJTextField.getText()),
					Double.parseDouble( tropicalMaxLaiJTextField.getText()), Double.parseDouble( temperateMaxLaiJTextField.getText()), Double.parseDouble( borealMaxLaiJTextField.getText()),
							Double.parseDouble( shrubMaxLaiJTextField.getText()), Double.parseDouble( gramineaMaxLaiJTextField.getText()), Double.parseDouble( aglbLimitJTextField.getText())};
    	configuration = new ConfigProperties(newValues[0],newValues[1],newValues[2],newValues[3],newValues[4],newValues[5],newValues[6],newValues[7],newValues[8],newValues[9],newValues[10]  	 );
    	setVisible(false);
    	}catch(NumberFormatException e){
    	
    		JOptionPane.showMessageDialog(getContentPane(), "Algum campo invalido", "Alerta", 1);
    		
    		
    	}
}

    private void resetarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarJButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_resetarJButtonActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aglbLimitJTextField;
    private javax.swing.JTextField borealBiomassJTextField;
    private javax.swing.JTextField borealMaxLaiJTextField;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JTextField gramineaBiomassJTextField;
    private javax.swing.JTextField gramineaMaxLaiJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton resetarJButton;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JTextField shrubBiomassJTextField;
    private javax.swing.JTextField shrubMaxLaiJTextField;
    private javax.swing.JTextField temperateBiomassJTextField;
    private javax.swing.JTextField temperateMaxLaiJTextField;
    private javax.swing.JTextField tropicalBiomassJTextField;
    private javax.swing.JTextField tropicalMaxLaiJTextField;
    // End of variables declaration//GEN-END:variables

}

